# Generated by Django 6.0.4 on 2026-05-03 20:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='data_added',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
