# Generated by Django 6.0.4 on 2026-05-04 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_animal_data_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='data_added',
            new_name='date_added',
        ),
    ]
